.compile make_cdf
.compile rcdf
.compile str2arr
.compile arr2str
.compile gt_brstr
.compile tag_exist
.compile str_replace
.compile mysql2idl_dtype
.compile mysql_client
.compile mysql_getdtype
.compile mysql_parsexml
.compile mysql_query
.compile chain2image
.compile display2d
.compile decode_votable